<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2015-2017, RoundCube Dev. - Venezuela                   |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: PICCORO Lenz McKAY <mckaygerhard@gmail.com>                        |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars']  = 'το Gravatar';
$labels['gravatar_enable_message']  = 'Εμφάνιση στην προβολή μηνυμάτων';
$labels['gravatar_enable_preview']  = 'Εμφάνιση σε προεπισκόπηση ';
$labels['gravatar_size'] = 'μέγεθος Gravatar';
$labels['gravatar_rating'] = 'Βαθμολογία grAvatar';
$labels['gravatar_default'] = 'Avatar από προεπιλογή, αν δεν υπάρχει ένα';
$labels['gravatar_border'] = 'Περίγραμμα γύρω από το avatar';
$labels['gravatar_none'] = 'κανένας';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';

?>

