<?php

/*

+-----------------------------------------------------------------------+
|                                                                       |
| Language file of the RoundCube show gravatar plugin                   |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: PICCORO Lenz MCKAY <mckaygerhard@gmail.com>                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['gravatars'] = 'Граватар';
$labels['gravatar_enable_message'] = 'Показывать граватар при чтении сообщения';
$labels['gravatar_enable_preview'] = 'Показывать граватар в превью сообщения';
$labels['gravatar_size'] = 'Размер аватара';
$labels['gravatar_rating'] = 'Аватар оценка';
$labels['gravatar_default'] = 'Аватар по умолчанию, если нет ни одного';
$labels['gravatar_border'] = 'Граница вокруг аватара';
$labels['gravatar_none'] = 'никто';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';

?>

